import authjs from "../assets/stack-images/auth-js.png";
import catalystui from "../assets/stack-images/catalyst-ui.png";
import clerk from "../assets/stack-images/clerk.png";
import css from "../assets/stack-images/css.png";
import firebase from "../assets/stack-images/firebase.png";
import git from "../assets/stack-images/git.png";
import github from "../assets/stack-images/github.png";
import headlessui from "../assets/stack-images/headless-ui.png";
import heroicons from "../assets/stack-images/heroicons.png";
import html from "../assets/stack-images/html.png";
import javascript from "../assets/stack-images/javascript.png";
import liquid from "../assets/stack-images/liquid.png";
import lucide from "../assets/stack-images/lucide.png";
import mongodb from "../assets/stack-images/mongodb.png";
import motion from "../assets/stack-images/motion.png";
import nest from "../assets/stack-images/nest-js.png";
import next from "../assets/stack-images/next-js.png";
import node from "../assets/stack-images/node-js.png";
import postgresql from "../assets/stack-images/postgresql.png";
import prisma from "../assets/stack-images/prisma-orm.png";
import radixui from "../assets/stack-images/radix-ui.png";
import react from "../assets/stack-images/react.png";
import redux from "../assets/stack-images/redux-js.png";
import resend from "../assets/stack-images/resend.png";
import shadcnui from "../assets/stack-images/shadcn-ui.png";
import shopify from "../assets/stack-images/shopify.png";
import sql from "../assets/stack-images/SQL.png";
import swiper from "../assets/stack-images/swiper.png";
import tailwindcss from "../assets/stack-images/tailwindcss.png";
import typescript from "../assets/stack-images/typescript.png";
import vite from "../assets/stack-images/vite.png";
import sass from "../assets/stack-images/sass.png";
import express from "../assets/stack-images/express-js.png";
import eslint from "../assets/stack-images/eslint.png";
import bun from "../assets/stack-images/bun.png";
import vercel from "../assets/stack-images/vercel.png";
import zod from "../assets/stack-images/zod.png";
import zustand from "../assets/stack-images/zustand.png";
import upstash from "../assets/stack-images/upstash.png";
import uploadthing from "../assets/stack-images/uploadthing.png";
import unsplash from "../assets/stack-images/unsplash.png";
import trpc from "../assets/stack-images/trpc.png";
import tiptap from "../assets/stack-images/tiptap.png";
import tanstack from "../assets/stack-images/tanstack.png";
import stripe from "../assets/stack-images/stripe.png";
import stream from "../assets/stack-images/stream.png";
import reactHookForm from "../assets/stack-images/react-hook-form.png";
import payload from "../assets/stack-images/payload.png";
import nuqs from "../assets/stack-images/nuqs.png";
import neon from "../assets/stack-images/neon.png";
import mux from "../assets/stack-images/mux.png";
import lodash from "../assets/stack-images/lodash.png";
import jotai from "../assets/stack-images/jotai.png";
import liveblocks from "../assets/stack-images/liveblocks.png";
import convex from "../assets/stack-images/convex.png";
import appwrite from "../assets/stack-images/appwrite.png";
import drizzle from "../assets/stack-images/drizzle.png";
import ngrok from "../assets/stack-images/ngrok.png";
import webhook from "../assets/stack-images/webhook.png";
import hono from "../assets/stack-images/hono.png";

export const stack = [
  {
    id: 1,
    name: "HTML",
    image: html,
    categories: ["Frontend Core"],
    learningLevel: 5,
    documentation: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    description:
      "HTML is the foundation of all web pages, a markup language that defines structure and content. I use semantic HTML to create accessible and SEO-optimized websites. Deep understanding of HTML5 elements allows me to create clean and logical structure. This is the foundation on which all my web projects are built.",
    skills: [
      "Semantic HTML5 elements",
      "Accessibility (ARIA, WCAG)",
      "SEO optimization",
      "Form validation",
      "Progressive enhancement",
      "Web APIs integration",
      "Web Components",
      "Performance optimization",
    ],
  },
  {
    id: 2,
    name: "CSS",
    image: css,
    categories: ["Frontend Core"],
    learningLevel: 4,
    documentation: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    description:
      "CSS allows me to create beautiful and responsive designs for web applications. I master modern technologies like Flexbox, Grid, animations and transitions. I use CSS variables, pseudo-classes and media queries for adaptive design. My approach includes mobile-first design and style performance optimization.",
    skills: [
      "Flexbox and CSS Grid",
      "Responsive design",
      "CSS animations & transitions",
      "CSS variables & custom properties",
      "Sass/SCSS preprocessing",
      "CSS-in-JS solutions",
      "Performance optimization",
      "Cross-browser compatibility",
    ],
  },
  {
    id: 3,
    name: "JavaScript",
    image: javascript,
    categories: ["Frontend Core"],
    learningLevel: 5,
    documentation: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    description:
      "JavaScript is the heart of web application interactivity, a programming language I use daily. I master ES6+ syntax, asynchronous programming and modern browser APIs. I create dynamic interfaces, handle events and work with DOM efficiently. My experience includes working with promises, async/await and modular architecture.",
    skills: [
      "ES6+ modern syntax",
      "Asynchronous programming",
      "DOM manipulation",
      "Event handling",
      "Module systems (ES6, CommonJS)",
      "Error handling & debugging",
      "Web APIs & Fetch",
      "Performance optimization",
    ],
  },
  {
    id: 4,
    name: "TypeScript",
    image: typescript,
    categories: ["Frontend Core", "Development Tools"],
    learningLevel: 4,
    documentation: "https://www.typescriptlang.org/docs/",
    description:
      "TypeScript improves my code quality through static typing and better development tools. I use it for large projects to avoid errors during development. I master interfaces, generics, enums and decorators for creating reliable applications. TypeScript allows me to write more predictable and maintainable code.",
    skills: [
      "Type system & interfaces",
      "Generics & advanced types",
      "Decorators & metadata",
      "Module augmentation",
      "Strict mode configuration",
      "Type guards & assertions",
      "Utility types",
      "TSConfig optimization",
    ],
  },
  {
    id: 5,
    name: "React",
    image: react,
    categories: ["React Ecosystem"],
    learningLevel: 5,
    documentation: "https://react.dev/",
    description:
      "React is my main library for creating user interfaces with component approach. I master hooks, context, component lifecycle and development patterns. I create reusable components and optimize performance using memoization. My experience includes working with forms, routing and state management.",
    skills: [
      "Hooks (useState, useEffect, custom)",
      "Context API & state management",
      "Component lifecycle",
      "Performance optimization",
      "JSX & rendering patterns",
      "Event handling",
      "Ref management",
      "Testing with React Testing Library",
    ],
  },
  {
    id: 6,
    name: "Next.js",
    image: next,
    categories: ["React Ecosystem", "Backend"],
    learningLevel: 4,
    documentation: "https://nextjs.org/docs",
    description:
      "Next.js is a powerful React framework for creating full-stack web applications with SSR and SSG. I use it for SEO-optimized sites and fast web applications. I master App Router, server components, API routes and image optimization. Next.js allows me to create performant applications with excellent user experience.",
    skills: [
      "App Router & file-based routing",
      "Server-side rendering (SSR)",
      "Static site generation (SSG)",
      "API routes & middleware",
      "Image optimization",
      "Server components",
      "Performance optimization",
      "Deployment strategies",
    ],
  },
  {
    id: 7,
    name: "Vite",
    image: vite,
    categories: ["React Ecosystem", "Development Tools"],
    learningLevel: 3,
    documentation: "https://vitejs.dev/",
    description:
      "Vite is a fast build tool that I use for developing modern frontend applications. Its fast Hot Module Replacement speeds up development process significantly. It supports TypeScript, JSX and other modern technologies out-of-the-box. Vite provides optimal performance both in development and production.",
    skills: [
      "Fast development server",
      "Hot Module Replacement (HMR)",
      "Build optimization",
      "Plugin ecosystem",
      "TypeScript integration",
      "Asset handling",
      "Environment variables",
      "Production bundling",
    ],
  },
  {
    id: 8,
    name: "Node.js",
    image: node,
    categories: ["Backend"],
    learningLevel: 4,
    documentation: "https://nodejs.org/en/docs/",
    description:
      "Node.js allows me to use JavaScript for server-side development and API creation. I develop RESTful services, handle files and work with databases. I master npm ecosystem, asynchronous programming and data streams. Node.js is the foundation for all my backend solutions and automation tools.",
    skills: [
      "Express.js framework",
      "RESTful API development",
      "File system operations",
      "Stream processing",
      "npm package management",
      "Event-driven architecture",
      "Middleware development",
      "Database integration",
    ],
  },
  {
    id: 9,
    name: "Nest.js",
    image: nest,
    categories: ["Backend"],
    learningLevel: 2,
    documentation: "https://nestjs.com/",
    description:
      "NestJS is an elegant framework for Node.js that uses decorators and TypeScript. I create scalable server applications with clean architecture and dependency injection. I use modular structure, middleware, guards and interceptors for robust APIs. NestJS provides enterprise-level quality for my backend code.",
    skills: [
      "Dependency injection",
      "Decorators & metadata",
      "Modular architecture",
      "Guards & interceptors",
      "Pipes & validation",
      "Database integration",
      "Authentication & authorization",
      "Testing strategies",
    ],
  },
  {
    id: 10,
    name: "Tailwind CSS",
    image: tailwindcss,
    categories: ["UI Libraries", "Development Tools"],
    learningLevel: 5,
    documentation: "https://tailwindcss.com/docs",
    description:
      "Tailwind CSS revolutionized my approach to styling through utility-first methodology. I create responsive designs faster with less custom CSS. I use configuration, components and directives to maintain consistent design system. Tailwind allows me to focus on functionality rather than writing CSS.",
    skills: [
      "Utility-first methodology",
      "Responsive design patterns",
      "Custom configuration",
      "Component extraction",
      "Plugin development",
      "Performance optimization",
      "Design system creation",
      "Dark mode implementation",
    ],
  },
  {
    id: 11,
    name: "Headless UI",
    image: headlessui,
    categories: ["UI Libraries"],
    learningLevel: 4,
    documentation: "https://headlessui.com/",
    description:
      "Headless UI provides ready-made accessible components without styles for React and Vue. I use it to create dropdown menus, modal windows and other interactive elements. Components have built-in support for keyboard navigation and screen readers. This allows me to focus on design while having solid accessibility foundation.",
    skills: [
      "Accessible component patterns",
      "Keyboard navigation",
      "Focus management",
      "ARIA attributes",
      "Modal & dialog handling",
      "Dropdown menus",
      "Toggle components",
      "Custom styling integration",
    ],
  },
  {
    id: 12,
    name: "Radix UI",
    image: radixui,
    categories: ["UI Libraries"],
    learningLevel: 3,
    documentation: "https://www.radix-ui.com/",
    description:
      "Radix UI is a low-level component library focused on accessibility and developer experience. I use its primitives to create custom design systems and complex UI patterns. Radix provides keyboard navigation, focus management and ARIA attributes. This is my go-to library for creating truly accessible interfaces.",
    skills: [
      "Primitive components",
      "Accessibility best practices",
      "Custom design systems",
      "Compound components",
      "Polymorphic components",
      "Event handling",
      "State management",
      "Animation integration",
    ],
  },
  {
    id: 13,
    name: "Shadcn UI",
    image: shadcnui,
    categories: ["UI Libraries"],
    learningLevel: 4,
    documentation: "https://ui.shadcn.com/",
    description:
      "Shadcn/ui combines Radix UI with Tailwind CSS to create beautiful and functional components. It's not a library, but a collection of copy-paste components that I can customize. Each component is written with TypeScript and has excellent accessibility support. Shadcn/ui accelerates development by providing ready but flexible solutions.",
    skills: [
      "Component customization",
      "Design system integration",
      "TypeScript implementation",
      "Accessibility patterns",
      "Theming strategies",
      "Copy-paste workflow",
      "Tailwind integration",
      "Component composition",
    ],
  },
  {
    id: 14,
    name: "Catalyst UI",
    image: catalystui,
    categories: ["UI Libraries"],
    learningLevel: 2,
    documentation: "https://catalyst.tailwindui.com/",
    description:
      "Catalyst UI is a modern React component library focused on enterprise applications. I use it to create professional interfaces with consistent design. Components are optimized for performance and have built-in TypeScript support. Catalyst provides comprehensive set of components for business applications.",
    skills: [
      "Enterprise component patterns",
      "Professional UI design",
      "Performance optimization",
      "TypeScript integration",
      "Business application patterns",
      "Consistent design language",
      "Scalable architecture",
      "Component documentation",
    ],
  },
  {
    id: 15,
    name: "Hero Icons",
    image: heroicons,
    categories: ["Icons & Assets"],
    learningLevel: 5,
    documentation: "https://heroicons.com/",
    description:
      "Hero Icons is a beautiful set of SVG icons created by Tailwind CSS team. I use them to create clean and consistent interfaces. Icons are available in outline and solid variants with different sizes. Hero Icons easily integrate with React components and Tailwind classes.",
    skills: [
      "SVG icon implementation",
      "Icon component creation",
      "Consistent iconography",
      "Outline & solid variants",
      "Size optimization",
      "Accessibility considerations",
      "React integration",
      "Custom icon libraries",
    ],
  },
  {
    id: 16,
    name: "Lucide",
    image: lucide,
    categories: ["Icons & Assets"],
    learningLevel: 3,
    documentation: "https://lucide.dev/",
    description:
      "Lucide is a modern icon set with beautiful and consistent design. I use Lucide icons to create intuitive interfaces with clear visual hierarchy. The library provides wide selection of icons for different categories and use cases. Lucide icons are easily customizable and integrate with any React projects.",
    skills: [
      "Modern icon design",
      "Consistent iconography",
      "Icon customization",
      "React component integration",
      "SVG optimization",
      "Accessibility standards",
      "Icon library management",
      "Design system integration",
    ],
  },
  {
    id: 17,
    name: "Framer Motion",
    image: motion,
    categories: ["Animation & Interaction"],
    learningLevel: 3,
    documentation: "https://www.framer.com/motion/",
    description:
      "Framer Motion allows me to create smooth and engaging animations for React applications. I use it for page transitions, component animations and interactive gestures. Motion API provides declarative approach to animations with powerful control over timing and easing. Framer Motion improves user experience by making interfaces more alive and responsive.",
    skills: [
      "Declarative animations",
      "Page transitions",
      "Gesture handling",
      "Animation variants",
      "Layout animations",
      "Performance optimization",
      "Complex choreography",
      "Interactive animations",
    ],
  },
  {
    id: 18,
    name: "Swiper",
    image: swiper,
    categories: ["Animation & Interaction"],
    learningLevel: 4,
    documentation: "https://swiperjs.com/",
    description:
      "Swiper is the most popular mobile touch slider library for creating carousels and sliders. I use it for image galleries, testimonials and product showcases. Swiper supports touch gestures, lazy loading and various transition effects. The library is performance-optimized and works smoothly on all devices.",
    skills: [
      "Touch gesture implementation",
      "Carousel creation",
      "Lazy loading strategies",
      "Transition effects",
      "Responsive breakpoints",
      "Performance optimization",
      "Custom navigation",
      "Event handling",
    ],
  },
  {
    id: 19,
    name: "Redux",
    image: redux,
    categories: ["State Management"],
    learningLevel: 3,
    documentation: "https://redux.js.org/",
    description:
      "Redux provides predictable state management for JavaScript applications through unidirectional data flow. I use Redux Toolkit to simplify boilerplate code and better developer experience. I create scalable architectures with clear action and reducer logic. Redux is especially useful for complex applications with multi-component state.",
    skills: [
      "Redux Toolkit (RTK)",
      "Action & reducer patterns",
      "Middleware development",
      "Async thunks",
      "State normalization",
      "DevTools integration",
      "Performance optimization",
      "Testing strategies",
    ],
  },
  {
    id: 20,
    name: "MongoDB",
    image: mongodb,
    categories: ["Databases"],
    learningLevel: 4,
    documentation: "https://www.mongodb.com/docs/",
    description:
      "MongoDB is a NoSQL database that I use for flexible and scalable data storage. I work with document-oriented data model through Mongoose ODM. I create efficient schemas, indexes and aggregation pipelines for optimal performance. MongoDB is perfect for rapid prototyping and applications with dynamic data structures.",
    skills: [
      "Document-based modeling",
      "Mongoose ODM",
      "Aggregation pipelines",
      "Index optimization",
      "Schema design",
      "Query optimization",
      "Replica sets",
      "Performance tuning",
    ],
  },
  {
    id: 21,
    name: "PostgreSQL",
    image: postgresql,
    categories: ["Databases"],
    learningLevel: 3,
    documentation: "https://www.postgresql.org/docs/",
    description:
      "PostgreSQL is a powerful open-source relational database with advanced features and ACID compliance. I use it for complex applications requiring data integrity and sophisticated queries. I work with triggers, stored procedures, JSON columns and full-text search capabilities. PostgreSQL provides enterprise-level reliability for critical business applications.",
    skills: [
      "Advanced SQL queries",
      "Stored procedures & functions",
      "JSON/JSONB operations",
      "Full-text search",
      "Index optimization",
      "Triggers & constraints",
      "Performance tuning",
      "Backup & recovery",
    ],
  },
  {
    id: 22,
    name: "SQL",
    image: sql,
    categories: ["Databases"],
    learningLevel: 4,
    documentation: "https://www.w3schools.com/sql/",
    description:
      "SQL is the query language for working with relational databases that I master at expert level. I create complex queries with joins, subqueries, window functions and common table expressions. I optimize performance through proper indexing, query planning and database design principles. SQL knowledge allows me to work efficiently with any relational databases.",
    skills: [
      "Complex query optimization",
      "Window functions",
      "Common table expressions",
      "Advanced joins",
      "Subqueries & correlated queries",
      "Index design",
      "Query execution plans",
      "Database normalization",
    ],
  },
  {
    id: 23,
    name: "Prisma ORM",
    image: prisma,
    categories: ["Databases", "Development Tools"],
    learningLevel: 4,
    documentation: "https://www.prisma.io/docs",
    description:
      "Prisma is a type-safe ORM that generates TypeScript client based on database schema. I use Prisma for database migrations, type-safe queries and excellent developer experience. Schema-first approach ensures consistency between database and application code. Prisma Studio provides convenient UI for database management and data visualization.",
    skills: [
      "Schema definition & migrations",
      "Type-safe query building",
      "Relation management",
      "Transaction handling",
      "Performance optimization",
      "Database introspection",
      "Prisma Studio usage",
      "Multi-database support",
    ],
  },
  {
    id: 24,
    name: "Firebase",
    image: firebase,
    categories: ["Backend Services", "Databases"],
    learningLevel: 3,
    documentation: "https://firebase.google.com/docs",
    description:
      "Firebase is Google platform for mobile and web development with comprehensive backend services. I use Firestore for real-time databases, Auth for authentication and Storage for file management. Firebase Functions allow creating serverless backend logic. This is ideal solution for rapid development and MVP creation with minimal backend complexity.",
    skills: [
      "Firestore database design",
      "Authentication strategies",
      "Cloud Functions",
      "Real-time synchronization",
      "Security rules",
      "File storage management",
      "Analytics integration",
      "Performance monitoring",
    ],
  },
  {
    id: 25,
    name: "Auth.js",
    image: authjs,
    categories: ["Authentication"],
    learningLevel: 3,
    documentation: "https://authjs.dev/",
    description:
      "Auth.js (NextAuth.js) is a complete authentication solution for Next.js applications. It supports OAuth providers, email/password auth and session management out-of-the-box. I use it for secure user authentication with JWT and database sessions. Auth.js provides security best practices and easy integration with various auth providers.",
    skills: [
      "OAuth provider integration",
      "JWT & session management",
      "Custom authentication flows",
      "Database adapters",
      "Security configurations",
      "Middleware implementation",
      "Role-based access control",
      "Custom signin pages",
    ],
  },
  {
    id: 26,
    name: "Clerk",
    image: clerk,
    categories: ["Authentication"],
    learningLevel: 4,
    documentation: "https://clerk.com/docs",
    description:
      "Clerk provides modern authentication and user management for web applications. I use it for seamless sign-up/sign-in flows with social providers and passwordless authentication. Clerk UI components are easily customizable and integrate with any design system. The platform ensures compliance, security and excellent developer experience for auth workflows.",
    skills: [
      "Modern authentication flows",
      "Social provider integration",
      "Passwordless authentication",
      "User management",
      "Custom UI components",
      "Security compliance",
      "Multi-tenant architecture",
      "Session management",
    ],
  },
  {
    id: 27,
    name: "Resend",
    image: resend,
    categories: ["Communication"],
    learningLevel: 2,
    documentation: "https://resend.com/docs",
    description:
      "Resend is a modern email API for developers that I use for transactional emails. It provides simple API for sending emails with excellent deliverability and analytics. It supports templates, attachments and webhook events for email tracking. Resend ensures reliable email delivery for user notifications and marketing campaigns.",
    skills: [
      "Email API integration",
      "Template management",
      "Deliverability optimization",
      "Webhook handling",
      "Analytics tracking",
      "Attachment handling",
      "Batch email sending",
      "Email validation",
    ],
  },
  {
    id: 28,
    name: "Git",
    image: git,
    categories: ["Development Tools"],
    learningLevel: 5,
    documentation: "https://git-scm.com/doc",
    description:
      "Git is a distributed version control system that I use daily for code management. I master advanced Git workflows including branching strategies, rebasing and conflict resolution. I use Git hooks, submodules and worktrees for complex project structures. Git allows me to collaborate effectively in teams and maintain clean project history.",
    skills: [
      "Advanced branching strategies",
      "Interactive rebasing",
      "Conflict resolution",
      "Git hooks implementation",
      "Submodules management",
      "Worktree operations",
      "History manipulation",
      "Collaborative workflows",
    ],
  },
  {
    id: 29,
    name: "GitHub",
    image: github,
    categories: ["Development Tools"],
    learningLevel: 5,
    documentation: "https://docs.github.com/",
    description:
      "GitHub is a platform for hosting Git repositories and collaboration where all my projects are stored. I use GitHub Actions for CI/CD, Issues for project management and Pull Requests for code review. I actively contribute to open-source projects and maintain own repositories. GitHub is the central hub for my development activity and portfolio.",
    skills: [
      "GitHub Actions CI/CD",
      "Pull request workflows",
      "Issue management",
      "Project boards",
      "Repository administration",
      "Open source contribution",
      "Security scanning",
      "Package publishing",
    ],
  },
  {
    id: 30,
    name: "Shopify",
    image: shopify,
    categories: ["E-commerce"],
    learningLevel: 3,
    documentation: "https://shopify.dev/docs",
    description:
      "Shopify is a leading e-commerce platform for which I develop custom themes and applications. I create responsive Shopify stores with custom functionality and integrations. I use Shopify API for headless commerce solutions and custom checkout experiences. My experience includes theme development, app creation and store optimization for maximum sales.",
    skills: [
      "Liquid template development",
      "Theme customization",
      "Shopify API integration",
      "App development",
      "Headless commerce",
      "Performance optimization",
      "SEO optimization",
      "Conversion optimization",
    ],
  },
  {
    id: 31,
    name: "Liquid",
    image: liquid,
    categories: ["E-commerce"],
    learningLevel: 4,
    documentation: "https://shopify.github.io/liquid/",
    description:
      "Liquid is a template language used in Shopify themes for dynamic content rendering. I master Liquid syntax for creating flexible and maintainable theme templates. I use filters, tags and objects for complex data manipulation and presentation logic. Liquid allows creating powerful e-commerce experiences with dynamic product catalogs and personalization.",
    skills: [
      "Template syntax mastery",
      "Filter implementation",
      "Object manipulation",
      "Conditional logic",
      "Loop structures",
      "Custom tag creation",
      "Performance optimization",
      "Debugging techniques",
    ],
  },
  {
    id: 32,
    name: "Sass",
    image: sass,
    categories: ["Frontend Core", "Development Tools"],
    learningLevel: 4,
    documentation: "https://sass-lang.com/documentation/",
    description:
      "Sass (Syntactically Awesome Style Sheets) is a CSS preprocessor that extends CSS with features like variables, nesting, and mixins. I use Sass to write more maintainable and organized stylesheets for complex projects. With features like partials, imports, and functions, Sass helps me create scalable design systems. It compiles to clean, standard CSS that works across all browsers.",
    skills: [
      "SCSS syntax & nesting",
      "Variables & mixins",
      "Partials & imports",
      "Functions & control directives",
      "Loops & conditionals",
      "Extend & placeholder selectors",
      "Build tool integration",
      "CSS architecture patterns",
    ],
  },
  {
    id: 33,
    name: "Express.js",
    image: express,
    categories: ["Backend"],
    learningLevel: 4,
    documentation: "https://expressjs.com/",
    description:
      "Express.js is a minimal and flexible Node.js web framework that provides robust features for web and mobile applications. I use Express to build RESTful APIs, handle middleware, and create server-side logic efficiently. It's my go-to framework for backend development with its simple yet powerful architecture. Express allows rapid development while maintaining scalability and performance.",
    skills: [
      "RESTful API development",
      "Middleware implementation",
      "Route handling & organization",
      "Error handling strategies",
      "Authentication & authorization",
      "Database integration",
      "Performance optimization",
      "Security best practices",
    ],
  },
  {
    id: 34,
    name: "ESLint",
    image: eslint,
    categories: ["Development Tools"],
    learningLevel: 4,
    documentation: "https://eslint.org/docs/latest/",
    description:
      "ESLint is a static code analysis tool for identifying and reporting patterns in JavaScript and TypeScript code. I use ESLint to maintain code quality, enforce coding standards, and catch potential bugs before they reach production. With custom rules and configurations, ESLint helps maintain consistent code style across team projects. It's essential for professional development workflows.",
    skills: [
      "Code quality enforcement",
      "Custom rule configuration",
      "Team coding standards",
      "Integration with IDEs",
      "Automated code fixing",
      "TypeScript support",
      "Plugin ecosystem",
      "CI/CD integration",
    ],
  },
  {
    id: 35,
    name: "Bun",
    image: bun,
    categories: ["Development Tools", "Backend"],
    learningLevel: 2,
    documentation: "https://bun.sh/docs",
    description:
      "Bun is an incredibly fast JavaScript runtime, package manager, test runner, and bundler all in one. I use Bun for its lightning-fast package installation and execution speed that significantly improves development workflow. With built-in TypeScript support and Node.js compatibility, Bun offers a modern alternative to traditional JavaScript tooling. It's perfect for rapid prototyping and performance-critical applications.",
    skills: [
      "Fast package management",
      "JavaScript runtime optimization",
      "Built-in bundling & transpilation",
      "TypeScript native support",
      "Node.js compatibility",
      "Testing framework integration",
      "Performance benchmarking",
      "Modern toolchain setup",
    ],
  },
  {
    id: 36,
    name: "Vercel",
    image: vercel,
    categories: ["Development Tools", "Backend Services"],
    learningLevel: 4,
    documentation: "https://vercel.com/docs",
    description:
      "Vercel is a cloud platform for static sites and serverless functions that I use for deploying Next.js applications. It provides instant deployments, automatic scaling, and edge network optimization. I leverage Vercel's seamless integration with GitHub for continuous deployment and preview environments. The platform offers excellent developer experience with zero-config deployments and real-time collaboration features.",
    skills: [
      "Next.js deployment optimization",
      "Serverless functions",
      "Edge network configuration",
      "Continuous deployment",
      "Preview environments",
      "Domain management",
      "Analytics integration",
      "Performance monitoring",
    ],
  },
  {
    id: 37,
    name: "Zod",
    image: zod,
    categories: ["Development Tools"],
    learningLevel: 4,
    documentation: "https://zod.dev/",
    description:
      "Zod is a TypeScript-first schema validation library that I use for runtime type checking and data validation. It provides excellent TypeScript inference and helps catch errors at both compile-time and runtime. I use Zod for form validation, API response validation, and environment variable parsing. Its declarative API makes complex validation logic readable and maintainable.",
    skills: [
      "Schema definition & validation",
      "TypeScript type inference",
      "Form validation patterns",
      "API response validation",
      "Custom validation logic",
      "Error handling strategies",
      "Runtime type checking",
      "Data transformation",
    ],
  },
  {
    id: 38,
    name: "Zustand",
    image: zustand,
    categories: ["State Management"],
    learningLevel: 3,
    documentation: "https://zustand-demo.pmnd.rs/",
    description:
      "Zustand is a lightweight state management library for React with a minimal boilerplate approach. I use it for simple and efficient state management without the complexity of Redux. Zustand provides a clean API for creating stores with TypeScript support and excellent developer experience. It's perfect for projects that need global state without over-engineering.",
    skills: [
      "Lightweight state stores",
      "TypeScript integration",
      "Minimal boilerplate",
      "Immer integration",
      "Persist middleware",
      "Devtools support",
      "Async actions",
      "Store composition",
    ],
  },
  {
    id: 39,
    name: "Upstash",
    image: upstash,
    categories: ["Backend Services", "Databases"],
    learningLevel: 2,
    documentation: "https://docs.upstash.com/",
    description:
      "Upstash provides serverless Redis and Kafka services with per-request pricing and instant scaling. I use it for caching, session storage, and real-time messaging in serverless applications. Upstash Redis offers REST API access, making it perfect for edge functions and JAMstack applications. The platform eliminates infrastructure management while providing Redis performance.",
    skills: [
      "Serverless Redis operations",
      "REST API integration",
      "Caching strategies",
      "Session management",
      "Edge computing compatibility",
      "Auto-scaling configuration",
      "Real-time messaging",
      "Performance optimization",
    ],
  },
  {
    id: 40,
    name: "UploadThing",
    image: uploadthing,
    categories: ["Backend Services"],
    learningLevel: 3,
    documentation: "https://docs.uploadthing.com/",
    description:
      "UploadThing is a file upload service built for Next.js applications with type-safe APIs and excellent developer experience. I use it for handling image uploads, file validation, and storage management. It provides React hooks, TypeScript support, and seamless integration with modern web frameworks. UploadThing simplifies file handling with built-in security and optimization.",
    skills: [
      "Type-safe file uploads",
      "React hooks integration",
      "File validation & processing",
      "Image optimization",
      "Security best practices",
      "Next.js integration",
      "Progress tracking",
      "Error handling strategies",
    ],
  },
  {
    id: 41,
    name: "Unsplash",
    image: unsplash,
    categories: ["APIs & Services"],
    learningLevel: 4,
    documentation: "https://unsplash.com/documentation",
    description:
      "Unsplash provides a powerful API for accessing high-quality stock photos and images for web applications. I integrate Unsplash API to dynamically fetch beautiful images for prototypes, galleries, and content creation. The service offers search functionality, collections, and user data with generous rate limits. Unsplash images enhance visual appeal of applications without copyright concerns.",
    skills: [
      "REST API integration",
      "Image search & filtering",
      "Dynamic image loading",
      "Rate limit management",
      "Image optimization",
      "Collection management",
      "Attribution handling",
      "Error handling & fallbacks",
    ],
  },
  {
    id: 42,
    name: "tRPC",
    image: trpc,
    categories: ["Backend", "Development Tools"],
    learningLevel: 3,
    documentation: "https://trpc.io/docs",
    description:
      "tRPC enables end-to-end type safety for APIs with TypeScript, eliminating the need for code generation. I use tRPC to create fully type-safe APIs between frontend and backend with excellent developer experience. It provides real-time subscriptions, middleware support, and seamless React integration. tRPC ensures API contracts are always in sync between client and server.",
    skills: [
      "End-to-end type safety",
      "API route creation",
      "React Query integration",
      "Middleware implementation",
      "Real-time subscriptions",
      "Error handling patterns",
      "Authentication integration",
      "Performance optimization",
    ],
  },
  {
    id: 43,
    name: "Tiptap",
    image: tiptap,
    categories: ["UI Libraries"],
    learningLevel: 2,
    documentation: "https://tiptap.dev/docs",
    description:
      "Tiptap is a headless rich-text editor framework built on ProseMirror with Vue.js and React support. I use it to create custom WYSIWYG editors with extensible functionality and modern UI components. Tiptap provides collaborative editing, real-time synchronization, and extensive customization options. It's perfect for creating content management systems and collaborative writing tools.",
    skills: [
      "Rich text editing",
      "Custom editor extensions",
      "Collaborative editing",
      "Real-time synchronization",
      "Custom UI components",
      "Content serialization",
      "Plugin development",
      "Performance optimization",
    ],
  },
  {
    id: 44,
    name: "TanStack Query",
    image: tanstack,
    categories: ["State Management", "Development Tools"],
    learningLevel: 4,
    documentation: "https://tanstack.com/query/latest",
    description:
      "TanStack Query (formerly React Query) is a powerful data-fetching library that manages server state with caching, synchronization, and background updates. I use it for efficient API data management, optimistic updates, and offline support. It provides automatic background refetching, stale-while-revalidate patterns, and excellent DevTools for debugging data flow.",
    skills: [
      "Server state management",
      "Caching strategies",
      "Background synchronization",
      "Optimistic updates",
      "Infinite queries",
      "Mutation handling",
      "Offline support",
      "Performance optimization",
    ],
  },
  {
    id: 45,
    name: "Stripe",
    image: stripe,
    categories: ["Backend Services", "E-commerce"],
    learningLevel: 3,
    documentation: "https://stripe.com/docs",
    description:
      "Stripe is a comprehensive payment processing platform that I integrate for handling online payments, subscriptions, and financial transactions. I use Stripe APIs for secure payment flows, webhook handling, and subscription management. The platform provides excellent developer tools, testing environments, and compliance features for building robust payment systems.",
    skills: [
      "Payment processing integration",
      "Subscription management",
      "Webhook implementation",
      "Security best practices",
      "PCI compliance",
      "Payment flow optimization",
      "Multi-currency support",
      "Analytics & reporting",
    ],
  },
  {
    id: 46,
    name: "Stream",
    image: stream,
    categories: ["Backend Services", "Communication"],
    learningLevel: 2,
    documentation: "https://getstream.io/docs/",
    description:
      "Stream provides scalable APIs for building activity feeds, chat applications, and video calling features. I use Stream for creating social features like news feeds, real-time messaging, and user interactions. The platform offers React components, real-time synchronization, and moderation tools. Stream handles the complexity of real-time features while maintaining performance at scale.",
    skills: [
      "Activity feed implementation",
      "Real-time chat systems",
      "Video calling integration",
      "React component library",
      "Real-time synchronization",
      "Moderation & content filtering",
      "Scalable architecture",
      "Performance optimization",
    ],
  },
  {
    id: 47,
    name: "React Hook Form",
    image: reactHookForm,
    categories: ["React Ecosystem", "Forms"],
    learningLevel: 4,
    documentation: "https://react-hook-form.com/",
    description:
      "React Hook Form is a performant library for managing forms in React with minimal re-renders and excellent developer experience. I use it for complex form validation, field arrays, and integration with UI libraries. It provides uncontrolled components approach, built-in validation, and TypeScript support. React Hook Form reduces boilerplate while maintaining flexibility and performance.",
    skills: [
      "Form state management",
      "Validation strategies",
      "Field arrays & dynamic forms",
      "UI library integration",
      "Performance optimization",
      "TypeScript integration",
      "Custom validation rules",
      "Error handling patterns",
    ],
  },
  {
    id: 48,
    name: "Payload CMS",
    image: payload,
    categories: ["Backend", "Content Management"],
    learningLevel: 2,
    documentation: "https://payloadcms.com/docs",
    description:
      "Payload is a headless CMS and application framework built with Node.js and TypeScript. I use Payload for creating custom admin panels, content management systems, and APIs with type safety. It provides authentication, file uploads, and GraphQL/REST APIs out of the box. Payload offers the flexibility of custom development with the convenience of a CMS.",
    skills: [
      "Headless CMS development",
      "Custom admin panels",
      "TypeScript configuration",
      "Authentication systems",
      "File management",
      "GraphQL & REST APIs",
      "Custom field types",
      "Access control patterns",
    ],
  },
  {
    id: 49,
    name: "nuqs",
    image: nuqs,
    categories: ["State Management", "React Ecosystem"],
    learningLevel: 3,
    documentation: "https://nuqs.47ng.com/",
    description:
      "nuqs is a type-safe library for managing URL search parameters as state in Next.js applications. I use it for creating shareable URLs, maintaining filter states, and browser navigation handling. It provides React hooks for URL state synchronization with TypeScript support and excellent developer experience. nuqs makes URL state management elegant and predictable.",
    skills: [
      "URL state management",
      "Type-safe search params",
      "React hooks integration",
      "Browser navigation",
      "State synchronization",
      "Next.js optimization",
      "Shareable URLs",
      "History management",
    ],
  },
  {
    id: 50,
    name: "Neon",
    image: neon,
    categories: ["Databases", "Backend Services"],
    learningLevel: 2,
    documentation: "https://neon.tech/docs",
    description:
      "Neon is a serverless PostgreSQL platform with branching, instant provisioning, and automatic scaling. I use Neon for modern applications requiring PostgreSQL with serverless benefits. It provides database branching for development workflows, connection pooling, and pay-per-use pricing. Neon combines PostgreSQL reliability with serverless convenience and developer productivity.",
    skills: [
      "Serverless PostgreSQL",
      "Database branching",
      "Connection pooling",
      "Auto-scaling configuration",
      "Development workflows",
      "Performance optimization",
      "Cost optimization",
      "Migration strategies",
    ],
  },
  {
    id: 51,
    name: "Mux",
    image: mux,
    categories: ["Backend Services", "Media"],
    learningLevel: 2,
    documentation: "https://docs.mux.com/",
    description:
      "Mux provides APIs for video streaming, encoding, and analytics that I integrate for building video-centric applications. I use Mux for video upload, processing, and delivery with adaptive streaming and global CDN. The platform offers real-time analytics, video security, and player components. Mux handles video infrastructure complexity while providing excellent viewer experiences.",
    skills: [
      "Video streaming integration",
      "Upload & encoding workflows",
      "Adaptive bitrate streaming",
      "Video analytics",
      "Player customization",
      "Security & DRM",
      "Global CDN optimization",
      "Real-time monitoring",
    ],
  },
  {
    id: 52,
    name: "Lodash",
    image: lodash,
    categories: ["Development Tools", "JavaScript Libraries"],
    learningLevel: 4,
    documentation: "https://lodash.com/docs",
    description:
      "Lodash is a modern JavaScript utility library providing consistent, modular, and performant functions for common programming tasks. I use Lodash for data manipulation, array operations, object transformations, and functional programming patterns. It offers tree-shaking support, TypeScript definitions, and battle-tested utility functions that improve code reliability and readability.",
    skills: [
      "Data manipulation utilities",
      "Array & object operations",
      "Functional programming patterns",
      "Performance optimization",
      "Tree-shaking integration",
      "TypeScript support",
      "Debouncing & throttling",
      "Deep cloning & comparison",
    ],
  },
  {
    id: 53,
    name: "Jotai",
    image: jotai,
    categories: ["State Management"],
    learningLevel: 3,
    documentation: "https://jotai.org/docs/introduction",
    description:
      "Jotai is a primitive and flexible state management library for React based on atomic approach. I use Jotai for bottom-up state management with excellent TypeScript support and minimal boilerplate. It provides fine-grained reactivity, async support, and composable atoms for complex state logic. Jotai eliminates prop drilling while maintaining predictable state updates.",
    skills: [
      "Atomic state management",
      "Bottom-up architecture",
      "Fine-grained reactivity",
      "Async atom handling",
      "State composition",
      "TypeScript integration",
      "Performance optimization",
      "Derivation patterns",
    ],
  },
  {
    id: 54,
    name: "Liveblocks",
    image: liveblocks,
    categories: ["Backend Services", "APIs & Services"],
    learningLevel: 2,
    documentation: "https://liveblocks.io/docs",
    description:
      "Liveblocks provides real-time collaboration APIs and React hooks for building collaborative applications like documents, whiteboards, and design tools. I use Liveblocks for presence awareness, live cursors, and collaborative editing features. It offers conflict-free data structures, offline support, and seamless synchronization. Liveblocks makes building multiplayer experiences straightforward and reliable.",
    skills: [
      "Real-time collaboration",
      "Presence awareness",
      "Conflict-free data structures",
      "Live cursors & selection",
      "Collaborative editing",
      "Offline synchronization",
      "React integration",
      "Performance optimization",
    ],
  },
  {
    id: 55,
    name: "Convex",
    image: convex,
    categories: ["Backend Services", "Databases"],
    learningLevel: 2,
    documentation: "https://docs.convex.dev/",
    description:
      "Convex is a backend-as-a-service platform providing reactive databases, serverless functions, and real-time synchronization. I use Convex for building full-stack applications with type-safe APIs and automatic data synchronization. It offers ACID transactions, optimistic updates, and seamless offline support. Convex eliminates backend complexity while providing enterprise-grade reliability.",
    skills: [
      "Reactive database operations",
      "Serverless function development",
      "Real-time synchronization",
      "Type-safe API development",
      "ACID transactions",
      "Optimistic updates",
      "Offline support",
      "Full-stack integration",
    ],
  },
  {
    id: 56,
    name: "Appwrite",
    image: appwrite,
    categories: ["Backend Services", "Databases"],
    learningLevel: 3,
    documentation: "https://appwrite.io/docs",
    description:
      "Appwrite is an open-source backend-as-a-service platform providing databases, authentication, storage, and serverless functions. I use Appwrite for rapid application development with built-in security, real-time subscriptions, and multi-platform SDKs. It offers self-hosted and cloud options with comprehensive APIs for web and mobile applications. Appwrite provides Firebase-like experience with full control and flexibility.",
    skills: [
      "Database design & queries",
      "Authentication strategies",
      "File storage management",
      "Serverless functions",
      "Real-time subscriptions",
      "Security configuration",
      "Multi-platform integration",
      "Self-hosting deployment",
    ],
  },
  {
    id: 57,
    name: "Drizzle ORM",
    image: drizzle,
    categories: ["Databases", "Development Tools"],
    learningLevel: 3,
    documentation: "https://orm.drizzle.team/docs/overview",
    description:
      "Drizzle ORM is a lightweight and performant TypeScript ORM for SQL databases with excellent developer experience. I use it for type-safe database queries with zero runtime overhead and SQL-like syntax. Drizzle provides automatic migrations, relation queries, and seamless integration with popular databases. It offers better performance than traditional ORMs while maintaining type safety and excellent TypeScript support.",
    skills: [
      "Type-safe SQL queries",
      "Schema definition & migrations",
      "Relation management",
      "Query builder optimization",
      "Database introspection",
      "Multi-database support",
      "TypeScript integration",
      "Performance optimization",
    ],
  },
  {
    id: 58,
    name: "ngrok",
    image: ngrok,
    categories: ["Development Tools", "Backend Services"],
    learningLevel: 4,
    documentation: "https://ngrok.com/docs",
    description:
      "ngrok is a secure tunneling service that exposes local servers to the internet for testing webhooks, APIs, and mobile applications. I use ngrok for local development when working with third-party services that require public URLs. It provides HTTPS tunnels, custom domains, and traffic inspection tools. ngrok is essential for testing webhook integrations and sharing local development environments.",
    skills: [
      "Local tunnel creation",
      "Webhook testing & debugging",
      "HTTPS tunnel management",
      "Traffic inspection & analysis",
      "Custom domain configuration",
      "API endpoint exposure",
      "Mobile app testing",
      "Third-party integration testing",
    ],
  },
  {
    id: 59,
    name: "Webhooks",
    image: webhook,
    categories: ["Backend Services", "APIs & Services"],
    learningLevel: 4,
    documentation: "https://webhooks.fyi/",
    description:
      "Webhooks are HTTP callbacks that enable real-time communication between applications by sending data when specific events occur. I implement and consume webhooks for payment processing, user notifications, and system integrations. They provide efficient event-driven architecture for connecting different services. Webhooks eliminate the need for constant polling and enable instant data synchronization.",
    skills: [
      "Webhook endpoint creation",
      "Event-driven architecture",
      "Payload validation & security",
      "Retry logic & error handling",
      "Signature verification",
      "Real-time data synchronization",
      "Third-party service integration",
      "Monitoring & logging",
    ],
  },
  {
    id: 60,
    name: "Hono",
    image: hono,
    categories: ["Backend"],
    learningLevel: 3,
    documentation: "https://hono.dev/",
    description:
      "Hono is a small, simple, and ultrafast web framework for the Edges. I use it for building lightweight APIs and serverless functions with excellent performance. It supports multiple JavaScript runtimes including Cloudflare Workers, Deno, Bun, and Node.js. Hono provides a simple API with built-in middleware and TypeScript support for rapid development.",
    skills: [
      "Edge computing optimization",
      "Multi-runtime support",
      "Lightweight API development",
      "Serverless functions",
      "Middleware implementation",
      "TypeScript integration",
      "Performance optimization",
      "Cloudflare Workers deployment",
    ],
  },
];
